env:
  global:
    secure: ZE++I+1Toaiqvm+P1RIrZWx+sA8Yz1SEeSIyR5WwxUxzOEwrm8GNuCGiL79T1eGQQv16jAxBI3Sqwi9Vbo7r/m2CYkiC8tT6JqmDPzsaEdMH2tnVsu1NdaUUuRucFOZeBKAcxBQgp9wbpIXFm6fnEaOAGE9t7BTGpPVzQJ4dAUAYf6y7f+wuW25mtOEjZkRxPsL0uyBvGU5koMMkvhXtoOjgLI64CN4ILBv/aWMjHCMZ1JmB4f/TFVgSTgC2kQ/zbpH7N92rbkiklxylBIUcTJxx6m57Q1s2+PgTTKK+UiPHsdADTMn0130BFNH+KFyBenmfqc/OjvOGw2AFD71tKzsDdDFapnRLyJ9oHfJ6hVYO1xEZA58OSfREpV/K0WCWkRWQ5TY5g5jWszt3HqGH/OtSIvH5mKv4Ark3r2oSTjRAjCncaBzcv6mGhQXDPpj7nvE0ew0TA4NUAVoCZJh0FzkDWvrXy2++SzHwjANPYUWd3G5TQVaZevTK+5vP9wQXw1cx2zuqAX2ENIfKddQcm9shzmHpvh/Y86ynZjJ+9DqSU4xS1qHFV6dbzhjKq+1Jlar6NKSuk8E8ukLgo2gn6UW1pYrhQoVf7Xq1Kr8HLUmEBF2cZqK6tBNKaa+atlJMsVmWViwktuU2a0OsFQ3Ven8w0yicj7FLTRKm9sO3ROI=
language: python
python:
- '3.4'
install:
- pip install -r requirements.txt
script: py.test
deploy:
- provider: script
  script: scripts/deploy.sh staging
  on:
    all_branches: true
