env:
  global:
  - secure: Uaxp8GK3ITJr9Q5/mcmoD6pjmz9jmGpiTUuB+6lEQiqXmXNe+1raeh6bUhaKhBiBxsl5MoCeDTeveukwbdoL29pQDNTUJGVF06N7YVV7QfVBZxeyI6M7xg9jO9Vz/h+1xUiT0iIxb6B/7K2ET4MluRsqaSwM7vlOeflkEKPhiJ2yDfr9plISHBnq2zgq3FE7CVawvkwtjqPHWecnfLjFHvtjZQRzdf3YyGDUZoaPojtDIz8i6gvXfFb69zZ4LO+Y5CjFt4TTQUDmJi5RjEFoGPRjSE11kGst6bDje6JqSufTKPL7lBUEqei9saz+6sWNoYEeaAHG7N+3PPd64feILVRt4oQJcWRbxfjid9UFK30aGs5knq41Q8q2DDTRxaIkgsx/TBfYlRPNKBnncw1IWyoaBdMLXJcy87Up+ZdSLwXVOQhdHwLcJRED8tOuPMWUue1tgkGvkC68Em+LRRqyC9/NqrG+Z0HGWHEY9PCEj5Pw/31n6ffd36kPYeoYtic4j+CbqvBVGxlf7SljCkO5Bn+/uKEv8fASh8m+hx4JnDGoVsRr5kdMcRCIG0zi8BUpkCSlRYFjAHYgGWdVLkimo+Ek5FU/pfpljkaxNaxtGaaSapjZ1HoYKA8dHTzDVYHtf7HOzBFQZ42/zw623zOOG434wHRhQZ98YB3i+LdrYNI=
  - secure: OVtSN6gXO27iDYfj8qCdTN5ItJ9r5xJfiTXLunBTX/rNXAcw1WiIgNAPC/re8Efx4yLmQ5YHeGVCSzOoLaNmUngG4bZjCU2nG9OEYN9857E8X4lpoJu7YgHnd3VCJl+s1954QCyXSd39BmoaJb4eJ/HZEZw7zF7K8Qe6RL2BCts/7Tz8iwuMmoevfeV6SHGITPkhFSiKgBqQ+DWflmUa01hMQ/W1pFZ0G20iFdcovw5q8+dL24aLmS/cQDcAkvgD5UOsBj73IYBzivQRWIx0H3Ql0KRAEcr1CluoGFIKdVX950Xh3Ntf0+0HIm18EB6r4xyLk446kXswNZOQWZV1I4fLJM9TtdbVVP71T6407K6rmjvWqoTjyy9YUuUZJVQTAYzKctcU2hX+ntNXKIovEquQo8Kp4sIAV98zgY8aO7/DwszVUYugkl9ONBqJVBkNVvGHOczc804VqxpZXofjOkw1taOylFynf9NyTOZudPhSYTKYgQftdLNQakRCAKBxSIQTfeT+BIUWroQTIBCLHC85riLKfArfqlJ280bewFu5OtQ3pQAL7Aa1ePV32LLDlF9t6+vsOstahOdPDlzzsE28sxu9fmXhqzC/Tg+4xz7nOEGvUPsA4RvChX3VnempR99uHUE6THpjISZvBVP10pk2JsBEqd9funetbX7XAJ0=
  - secure: cG2tUJ3AaU8UTcKj275dq/kMZ9yhtpWOgj32c9OdSDzUACsJpaiRLJ85+Wnd2WKsbZ+rlziltwRlih/WMGMllugWST2Wdrilx7eh/JBarncLbrG85fbbPvrcX5CORMOmiQ6TDvdrNEl8T3IzAPfqtzvcVoSuSD6gMSoKszu/eQC39NOXkP5yPWSFY//1SywINPdpvYMkoLWIbguwqb520YO2wwVlP/zNjwX+DkObVXBIWsMgzUMj6RNaNKYtcgQP2Y4TnRZlhO5xx6t01MjH4cmryqMQD+S3HQcyjru30wO/iw2hIYXroddYbA7qyoQ3agUibeHc5Ro3zbYsyc/xe2UW/LDkBIv1tLncTeoCaYbgHK44mhGfgn8PfQXcwqttAatznhNjbq5v0cH19fxZVjiBe6D6wTcFCRCDUGKoUQLRGSxlqysvzktiSOK2BRCxWqrqwbVaglAubNbi9Ewy8xiI8l+AoPZk2cAjlWSk4KVJ02rK7JaFdDUWVRrWIj6vOr8C7l9NaDHfr2RhWU9X7Nah6jBA0W055KwsY7YGDiYFqyfAXfAreocayZyszD1fqJmtJm5e1U+1FH0xho4A48lEM9Wh/L6U2mkdS0Hyf62GMpcjxwxHBkWP3G/+yeRxAlV6T8mK8vIAAl8LgCVzDOMdN2bYm4pmbeQbxaIr5uU=
sudo: required
services:
- docker
language: python
python:
- '3.4'
install:
- pip install -r requirements.txt
- pip install python-openstackclient
  #- docker-compose build
script: py.test
after_success:
- docker images
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- scripts/deploy.sh staging
deploy:
- provider: script
  script: scripts/deploy.sh staging
  on:
    all_branches: true
notifications:
  slack:
    secure: fqUk6dUppIZx6cFUuHazfRWSnEvSEeuiX3Owzn/isBanpA0LRd37+Wq+UIeZ8v6qUYfebuiO8MP9fwV/eyZgJglEKjDgksuV4X5dFyxhN8mMFjMf0E5WXneAVU6NRHe3bFqEQx9FPUYEwmkZLIdbQfAwoMfhn/D1vRfEka3iLJdIjbUx/pAWEpBYCoQ4i817frqgZG0hrT+Btz8ICjfXtEjQ+FRJOWPkRtkrLFd25GE2Fl9ZIvTgArz95G6R48CBsYrUvyR4VDhWNDYslMOj+UtUwjS8x4+y9Y+QiKfXiK7jYvjcGcYqsXnXKloawtYc/QBTrhiaTMefsfsvrIKb0JmDlfyXMod+LK/QvQQz/egsbX1wyWE0JSPTANOeaafgEiWSv9dkmcsGQFGwxbXx++xk0dJahC5u85XMRJc5wV9Prx5hcpMC1s1g6BpcuZvMv+yWlohDXCbT9Bcgo2P2mhuFWutfPccjnyYpBhkfQ8qQn+OyaOtZeCJAiXsUorGJBcK5Gwl0SlsTjykkrwpr3WczHz19OyXYxEcEk1QHeCkxN11qR2/XOe5QCCwKKLGmPvnkhMH19sBit4k4CVQ82pWLDwoiPs0Xeq718J+e7JIQ+JWL+JO0aZy/B5XeBcyFJ2BbcCDUgB6saqrXQKW3VH0IS0RvYd4p/hQH/xT+QfY=
