env:
  global:
  - secure: ffg02AIDEWr0pJcfOvkUuSHeY5mbQQtFfHHZ3rl0AEifVv0BWFz1ozX67DzA4nyigh1AKHGSaugD23Ke6Gcjmt0uqhQrKk4iAKZI0LsIJVTC9e4gmtOmNIX/pjcfgagP2AmzfATDIzIjX5kdGC7nXXQbqlxK/HmB4bXEjFLDnJjRpaA5ODgGUV2BMsj6yG1k66dMVuv1Tln7m/XK+DaSeDr+1b7XWDdzDwbUxZupSxO2onc0O10rsut3CY1dFVHlc4jWFMEGyC8wtbNZ+HkYODT8VmHlXCfLtPEhdat9VvqO7jvDTE1uA2/ncW+i+M0XyTIPO3GNMK9VDSj/OLhkA2NI+9Dkw8x0iyxo1OLLz7W3bRd5ShvZ6MaxrYDeEvXmeazUNOHKpHvKaw/MTRNZNUB1nfJ/RZjdIcpea46BfKI4Gu/DAcZ+JMECuQ4Il5OL/XBVzQgnE+IbbeiYVE0IM8VbwCQ2SZuJSG8gC85cqqkJpqLotWWVFpqtT2Y29hiV9me7s2iyc/uNCdsKSBdzHwCnzOLU+D23DmvHPwidSJATiIEngr3jly8mDL7Uo3GQ8d6ZsAW3AHwHq/qljz8xYY3D4Tu5pP6NOLv3F0afLHgQQQNCWJYEf7ZBCs8RIjE6qcXI80Ji0no2LYowlKV1pYaeInZBFidhdKr8QXYax0E=
  - secure: QIi7v8Zoim1ONyO8Ab/OElC1GssnuVpLBCQlNuw89QE0pDFVuz5iVdV+rhoFH0Gm+1oaZndOvwdDXi3Sjr3zPJhnFs4IRHcuGfPTZkMWFUMZdcyi3HCgDaDFVfpAHrSNp13tzrC7SDHvz4y6o15nGdnYeYGhtRk4Y/UILjMznCxl4XaLUq/utUBy/4kdl8fItYNtK+CYwYAxsV4TV4hFp/8uSh537/Ldxnl9pkkaIsWYhaSrSHTjquXQIgVhjLnSTG72jyGKXztIkcFIblNjDiCvibFD9B2b+8JvaOd0UX9/UkS4ujNpKYqzjSUel9VfVAINuFHSgaQa7GSdAQXRgSqrX25EpnI82emhig5l9asJvvOlGbx8DEJHDpDOFtmrykbDArDGSxyuXDwpqY0DYRtlRGV4dgJ1l/Bm4wd4RPONU9T3hl8hDtt115XwBlOPGE7uQyPQOiP8+08xS+uG3ZvMTmB3k31yZHuProk9nNz74zMJKdU1eBWSYy4NxWQH6xdnc2HCi5Ykebh2YrZZmyWSMyTLIl8r+/3Eas3dVrotF3P6xncm3jThlGFmh60F3AAgCHWYgr4lcaihsNJK59VnDAvOFDicuI5lXrBal0xub8RnRmAxQgBcxvLD7oB+F4HlV1vsdiPB6NBxAbduXWXNPV/m4acwZFgkvcQcCGA=
  - secure: pZ+ymEZXv0DoS5HpQ7TRInR2R3vPvvNnTaFYqmPvigTbBuL9Q7ksJeCLA7Tq3DSInp34PQHBqV+SKbZkj2ItRJALFRHzU+sUQOnH7kEBpgqXMnDmCkKLIKZNe9KLpbh/ZvrUvftCL4zVLwMSx8mFoOxG8kXQyBeJ8j7EdwrUpE0mW7uxy7HUPOb/W6ucg6UT3K/ujJOr4l9JWsnE135d1bVgAf+zuZOhaXls7zS7xQ0mN7R+rw5VlRBvcTX2i4Fksk/V0uCKLVXSq9S6imMabgR3rOXqKWx8wuBKJdjRSglh4xeAdLATdynCC0hg51V0aP9RsoaMqlHQT7ac3MroGKG2Do5zm3r/eqp20VJ8YR1AQ6ZLzoFtCSohQBbgb/e4Zz3AmEt0x/p2JEKtZ3VlA5xDBAe3nr0tlf6O0opKAgM63oY552JfhVyTXr12FyGda8W1qK8dp3pDxpsYSG6bt3BQANhOCB+IVPtTQ9P7zuvLed81bYr9YQW7Si/+Vio32rL6tIPve68Dsg70ew2/DqdkdbadkSp/hvevXz5If7vTtdLsiDq6wDD3S7TIKHl3u/tnqTsAMagNOYNcvLBQQxz29Io/lUlmMEzy7OeQARH/BG7DHmElUUH2zur5955epmfXinBZdf4XNl5PSAGPbFOs7vB5JgQyxkHIFzrYoZ8=
sudo: required
services:
- docker
language: python
python:
- '3.4'
install:
- pip install -r requirements.txt
- pip install python-openstackclient
- docker-compose build
script: py.test
after_success:
- docker images
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- export OS_PASSWORD="$OS_PASSWORD"
- openstack server list
deploy:
- provider: script
  script: scripts/deploy.sh staging
  on:
    all_branches: true
notifications:
  slack:
    secure: fqUk6dUppIZx6cFUuHazfRWSnEvSEeuiX3Owzn/isBanpA0LRd37+Wq+UIeZ8v6qUYfebuiO8MP9fwV/eyZgJglEKjDgksuV4X5dFyxhN8mMFjMf0E5WXneAVU6NRHe3bFqEQx9FPUYEwmkZLIdbQfAwoMfhn/D1vRfEka3iLJdIjbUx/pAWEpBYCoQ4i817frqgZG0hrT+Btz8ICjfXtEjQ+FRJOWPkRtkrLFd25GE2Fl9ZIvTgArz95G6R48CBsYrUvyR4VDhWNDYslMOj+UtUwjS8x4+y9Y+QiKfXiK7jYvjcGcYqsXnXKloawtYc/QBTrhiaTMefsfsvrIKb0JmDlfyXMod+LK/QvQQz/egsbX1wyWE0JSPTANOeaafgEiWSv9dkmcsGQFGwxbXx++xk0dJahC5u85XMRJc5wV9Prx5hcpMC1s1g6BpcuZvMv+yWlohDXCbT9Bcgo2P2mhuFWutfPccjnyYpBhkfQ8qQn+OyaOtZeCJAiXsUorGJBcK5Gwl0SlsTjykkrwpr3WczHz19OyXYxEcEk1QHeCkxN11qR2/XOe5QCCwKKLGmPvnkhMH19sBit4k4CVQ82pWLDwoiPs0Xeq718J+e7JIQ+JWL+JO0aZy/B5XeBcyFJ2BbcCDUgB6saqrXQKW3VH0IS0RvYd4p/hQH/xT+QfY=
