env:
  global:
  - secure: ZE++I+1Toaiqvm+P1RIrZWx+sA8Yz1SEeSIyR5WwxUxzOEwrm8GNuCGiL79T1eGQQv16jAxBI3Sqwi9Vbo7r/m2CYkiC8tT6JqmDPzsaEdMH2tnVsu1NdaUUuRucFOZeBKAcxBQgp9wbpIXFm6fnEaOAGE9t7BTGpPVzQJ4dAUAYf6y7f+wuW25mtOEjZkRxPsL0uyBvGU5koMMkvhXtoOjgLI64CN4ILBv/aWMjHCMZ1JmB4f/TFVgSTgC2kQ/zbpH7N92rbkiklxylBIUcTJxx6m57Q1s2+PgTTKK+UiPHsdADTMn0130BFNH+KFyBenmfqc/OjvOGw2AFD71tKzsDdDFapnRLyJ9oHfJ6hVYO1xEZA58OSfREpV/K0WCWkRWQ5TY5g5jWszt3HqGH/OtSIvH5mKv4Ark3r2oSTjRAjCncaBzcv6mGhQXDPpj7nvE0ew0TA4NUAVoCZJh0FzkDWvrXy2++SzHwjANPYUWd3G5TQVaZevTK+5vP9wQXw1cx2zuqAX2ENIfKddQcm9shzmHpvh/Y86ynZjJ+9DqSU4xS1qHFV6dbzhjKq+1Jlar6NKSuk8E8ukLgo2gn6UW1pYrhQoVf7Xq1Kr8HLUmEBF2cZqK6tBNKaa+atlJMsVmWViwktuU2a0OsFQ3Ven8w0yicj7FLTRKm9sO3ROI=
  - secure: yHLqliR6McUxF8+reqpNPn9lNBBg1eSX4PrGhhR2DB91DLmG8nOnKlU/O1+7j/lm8LlKIg+ia3Zcs3sPX6kYfBx+wZ4bVYRIOLKRqpLSNKEp+K37vGi1K88OjVmf2rU4WQ1STQBQ2PDJs7idukSiAYNGpA0dumT6lfjhFTwO+Udf9pi40XFDrbZtlMWwMj/NBm3wFhCtNPNsHv2oG97DhkzMWXvyFqpHPvPtLAKcLsi9rwFSLSUJM5K5G8v+tnICTWF4/C8DwYkFGo2V3TLKdP1QQAs8LobqFrmIt7hINTsR3zOSgnJiHTrWTnWOk31QRr3XGhjqdvbyJjNDHCaVHM7IgPTbJye4H87fFNZUex8PB7fd9R6BY0Ntl17LeAl8u+3H/HkPfGGYCPbYRpsBzvLqQ2GRrUDm6YmVfOV+wFcEU6TlwLWu7GKMVM+MkzUfEU0hyiCntLVd85bSMtQ6z3Gq9QSGbCZzAtWMwqa0WyPidq6M8e+nHVl2WGO3E1kPXmqo+mH8hviJ6Z2V2H9tqoMyecb+F1qyD/4hKIkQhkzRY581jvJezJ0PjZMDj1vKiNvcd25vAY1DrTWgDLMmWxBbVGFA9tSwk6vQDck8ikdFMEcGN+LsQmCrf+D5pzK9rDgW/8eNdCCYNeO51CIwG+kTKtmD1sDOXqPGrhImRO4=
sudo: required
services:
  - docker
language: python
python:
- '3.4'
install:
- pip install -r requirements.txt
- pip install python-openstackclient
script: py.test
deploy:
- provider: script
  script: scripts/deploy.sh staging
  on:
    all_branches: true
notifications:
  slack:
    secure: fqUk6dUppIZx6cFUuHazfRWSnEvSEeuiX3Owzn/isBanpA0LRd37+Wq+UIeZ8v6qUYfebuiO8MP9fwV/eyZgJglEKjDgksuV4X5dFyxhN8mMFjMf0E5WXneAVU6NRHe3bFqEQx9FPUYEwmkZLIdbQfAwoMfhn/D1vRfEka3iLJdIjbUx/pAWEpBYCoQ4i817frqgZG0hrT+Btz8ICjfXtEjQ+FRJOWPkRtkrLFd25GE2Fl9ZIvTgArz95G6R48CBsYrUvyR4VDhWNDYslMOj+UtUwjS8x4+y9Y+QiKfXiK7jYvjcGcYqsXnXKloawtYc/QBTrhiaTMefsfsvrIKb0JmDlfyXMod+LK/QvQQz/egsbX1wyWE0JSPTANOeaafgEiWSv9dkmcsGQFGwxbXx++xk0dJahC5u85XMRJc5wV9Prx5hcpMC1s1g6BpcuZvMv+yWlohDXCbT9Bcgo2P2mhuFWutfPccjnyYpBhkfQ8qQn+OyaOtZeCJAiXsUorGJBcK5Gwl0SlsTjykkrwpr3WczHz19OyXYxEcEk1QHeCkxN11qR2/XOe5QCCwKKLGmPvnkhMH19sBit4k4CVQ82pWLDwoiPs0Xeq718J+e7JIQ+JWL+JO0aZy/B5XeBcyFJ2BbcCDUgB6saqrXQKW3VH0IS0RvYd4p/hQH/xT+QfY=
